"""widen connector token columns to text

Revision ID: 4623631fb25b
Revises: 614ecc5a0ea1
Create Date: 2026-08-18 14:36:24.821348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4623631fb25b"
down_revision: Union[str, Sequence[str], None] = "614ecc5a0ea1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connector_credentials",
        "access_token_encrypted",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "connector_credentials",
        "refresh_token_encrypted",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connector_credentials",
        "refresh_token_encrypted",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=True,
    )
    op.alter_column(
        "connector_credentials",
        "access_token_encrypted",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
