"""connector credentials and ingested items

Revision ID: 614ecc5a0ea1
Revises: c7a254413b75
Create Date: 2026-08-18 00:38:34.884445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '614ecc5a0ea1'
down_revision: Union[str, Sequence[str], None] = 'c7a254413b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(length=2048), nullable=True),
    sa.Column('scope', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_account_label', sa.String(length=255), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_connector_user_provider')
    )
    op.create_index(op.f('ix_connector_credentials_user_id'), 'connector_credentials', ['user_id'], unique=False)
    op.create_table('ingested_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'source_type', 'external_id', name='uq_ingested_item_identity')
    )
    op.create_index('ix_ingested_items_embedding', 'ingested_items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_ingested_items_occurred_at'), 'ingested_items', ['occurred_at'], unique=False)
    op.create_index('ix_ingested_items_search_vector', 'ingested_items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_ingested_items_user_id'), 'ingested_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_items_user_id'), table_name='ingested_items')
    op.drop_index('ix_ingested_items_search_vector', table_name='ingested_items', postgresql_using='gin')
    op.drop_index(op.f('ix_ingested_items_occurred_at'), table_name='ingested_items')
    op.drop_index('ix_ingested_items_embedding', table_name='ingested_items', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('ingested_items')
    op.drop_index(op.f('ix_connector_credentials_user_id'), table_name='connector_credentials')
    op.drop_table('connector_credentials')
    # ### end Alembic commands ###
