"""add flaky test workflow runs table

Revision ID: 87775288daf2
Revises: d4d52936192c
Create Date: 2026-08-19 23:50:29.585979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87775288daf2'
down_revision: Union[str, Sequence[str], None] = 'd4d52936192c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flaky_test_workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('run_attempt', sa.Integer(), nullable=False),
    sa.Column('head_branch', sa.String(length=255), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('conclusion', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('html_url', sa.String(length=2048), nullable=False),
    sa.Column('pull_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo', 'run_id', name='uq_flaky_run_user_repo_run_id')
    )
    op.create_index('ix_flaky_run_user_repo', 'flaky_test_workflow_runs', ['user_id', 'repo'], unique=False)
    op.create_index(op.f('ix_flaky_test_workflow_runs_user_id'), 'flaky_test_workflow_runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flaky_test_workflow_runs_user_id'), table_name='flaky_test_workflow_runs')
    op.drop_index('ix_flaky_run_user_repo', table_name='flaky_test_workflow_runs')
    op.drop_table('flaky_test_workflow_runs')
    # ### end Alembic commands ###
