"""add first_attempt_conclusion to flaky test workflow runs

Revision ID: c79676dc562f
Revises: fe5b6084f7b4
Create Date: 2026-08-20 01:42:44.699831

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c79676dc562f"
down_revision: str | Sequence[str] | None = "fe5b6084f7b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flaky_test_workflow_runs",
        sa.Column("first_attempt_conclusion", sa.String(length=32), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flaky_test_workflow_runs", "first_attempt_conclusion")
    # ### end Alembic commands ###
