"""add last_synced_at to connector credentials

Revision ID: d4d52936192c
Revises: 4623631fb25b
Create Date: 2026-08-19 22:58:19.475765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4d52936192c"
down_revision: Union[str, Sequence[str], None] = "4623631fb25b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connector_credentials",
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connector_credentials", "last_synced_at")
    # ### end Alembic commands ###
